# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml

name: riboseq_env
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::pigz=2.3.4
  - conda-forge::glob2=0.7
  - bioconda::fastqc=0.11.9
  - bioconda::cutadapt=4.1
  - bioconda::star=2.7.10b
  - bioconda::bedtools=2.30.0
  - bioconda::umi_tools=1.1.2
  - bioconda::samtools=1.11
  - bioconda::multiqc=1.10.1
  - bioconda::pysam=0.16.0.1
  - bioconda::snakemake=7.18.1
  - bioconda::bowtie2=2.5.0

  # R packages
  - conda-forge::r-base=4.0.3
