# Other MultiQC config stuff here
custom_data:
  starting_length:
    parent_id: read_length
    parent_name: "Read Length"
    file_format: "tsv"
    section_name: "Starting Read Length Distribution"
    description: "Length distribution for reads."
    plot_type: "linegraph"
    pconfig:
      id: "starting_length_linegraph"
      title: "Starting Read Length Distribution"
      xlab: Length (nt)
      ylab: Frequency
      yDecimals: False
  useful_length:
    parent_id: read_length
    parent_name: "Read Length"
    file_format: "tsv"
    section_name: "Useful Read Length Distribution"
    description: "Length distribution for reads that uniquely map to protein-coding transcripts."
    plot_type: "linegraph"
    pconfig:
      id: "useful_length_linegraph"
      title: "Read Length Distribution"
      xlab: Length (nt)
      ylab: Frequency
      yDecimals: False
  region_counts:
    parent_id: riboseq_qc
    parent_name: "Ribo-seq QC"
    file_format: "tsv"
    section_name: "Regions"
    description: "Distribution of protein-coding transcripts mapping reads over UTR and CDS regions."
    plot_type: "bargraph"
    pconfig:
      id: "region_counts_barplot"
      title: "Regions"
      cpswitch: True
  mapping_counts:
    parent_id: mapping
    parent_name: "Mapping"
    file_format: "tsv"
    section_name: "Mapping"
    description: "Mapping results."
    plot_type: "bargraph"
    pconfig:
      id: "mapping_counts_barplot"
      title: "Mapping"
      cpswitch: True
  start_dist:
    parent_id: riboseq_qc
    parent_name: "Ribo-seq QC"
    file_format: "tsv"
    section_name: "Distance from START codon"
    description: "Distance of 5'ends of reads of expected length from START codon. Unless specified, the expected read length range is between 26 and 32 nt."
    plot_type: "linegraph"
    pconfig:
      id: "start_dist_linegraph"
      title: "Distance from START codon"
      xlab: Distance from START codon (nt)
      ylab: Count
      yDecimals: False
  ribocutter:
    parent_id: ribocutter
    parent_name: "Ribocutter"
    file_format: "tsv"
    section_name: "Ribocutter"
    description: "Percentage of reads targeted by guides designed by Ribocutter (50 guides by default) using two different read length thresholds. The higher the proportion targeted, the better."
    plot_type: "bargraph"
    pconfig:
      id: "ribocutter_barplot"
      title: "Ribocutter: proportion of reads targeted"
      ylab: "Percentage reads targeted (%)"
      xmax: 100
      xmin: 0
      cpswitch: False
      stacking: null
  frame_counts:
    parent_id: riboseq_qc
    parent_name: "Ribo-seq QC"
    file_format: "tsv"
    section_name: "Frame"
    description: "Frame distribution for reads in the expected length range."
    plot_type: "bargraph"
    pconfig:
      id: "frame_counts_barplot"
      title: "Frame"
      cpswitch: False
      stacking: null
  pcoding_percentage:
    parent_id: riboseq_qc
    parent_name: "Ribo-seq QC"
    parent_description: "This section contains various Ribo-seq quality control metrics."
    file_format: "tsv"
    section_name: "Protein-coding Genes Mapping Percentage"
    description: "Percentage of reads mapping uniquely to protein-coding transcripts. This is the proprtion of reads of the entire library that are useful for most downstream analyses. For each gene, a single representative transcript was used (by default, the one with the longest CDS was used). The higher the percentage, the better."
    plot_type: "bargraph"
    pconfig:
      id: "pcoding_percentage_barplot"
      title: "Reads mapping to protein-coding transcripts"
      ylab: "Percentage (%)"
      xmax: 100
      xmin: 0
      cpswitch: False
      stacking: null
      tt_percentages: False
      use_legend: False
  expected_length:
    parent_id: riboseq_qc
    parent_name: "Ribo-seq QC"
    parent_description: "This section contains various Ribo-seq quality control metrics, summarised across all samples. More detailed QC metrics regarding the quality of the Ribo-seq data can be found in the sample-specific reports."
    file_format: "tsv"
    section_name: "Expected Read Length Percentage"
    description: "Percentage of uniquely mapping reads to protein-coding transcripts of expected RPF length. The higher the percentage, the better. Unless specified, the expected read length range is between 26 and 32 nt."
    plot_type: "bargraph"
    pconfig:
      id: "expected_length_barplot"
      title: "Reads of expected length"
      ylab: "Percentage (%)"
      xmax: 100
      xmin: 0
      cpswitch: False
      stacking: null
      tt_percentages: False
      use_legend: False
  duplication:
    parent_id: riboseq_qc
    parent_name: "Ribo-seq QC"
    parent_description: "This section contains various Ribo-seq quality control metrics."
    file_format: "tsv"
    section_name: "Duplication"
    description: "Percentage of duplicated reads of expected RPF length based on UMIs. Unless specified, the expected read length range is between 26 and 32 nt."
    plot_type: "bargraph"
    use_legend: False
    pconfig:
      id: "duplication_barplot"
      title: "Duplication"
      ylab: "Percentage (%)"
      xmax: 100
      xmin: 0
      cpswitch: False
      stacking: null
      tt_percentages: False
  pca:
    parent_id: pca
    parent_name: "PCA"
    section_name: "PCA Analysis"
    description: "This plot shows the first two components from a principal component analysis on RPF counts from FeatureCounts and P-site counts on CDS."

sp:
  starting_length:
    fn: "starting_length_mqc.tsv"
  useful_length:
    fn: "useful_length_mqc.tsv"
  region_counts:
    fn: "region_counts_mqc.tsv"
  start_dist:
    fn: "start_dist_mqc.tsv"
  ribocutter:
    fn: "ribocutter_mqc.tsv"
  pca:
    fn: "pca_mqc.png"
  pcoding_percentage:
    fn: "pcoding_percentage_mqc.tsv"
  expected_length:
    fn: "expected_length_mqc.tsv"
  duplication:
    fn: "duplication_mqc.tsv"
  mapping_counts:
    fn: "mapping_counts_mqc.tsv"
  frame_counts:
    fn: "frame_counts_mqc.tsv"

module_order:
    - mapping
    - read_length
    - pca
    - riboseq_qc
    - ribocutter
    - fastqc
    - bowtie2
    - star

export_plots: false