# Other MultiQC config stuff here
custom_data:
  ribocutter:
    file_format: "tsv"
    section_name: "Ribocutter"
    description: "This plot comes from files acommpanied by a mutliqc_config.yaml file for configuration"
    plot_type: "bargraph"
    pconfig:
      id: "ribocutter_barplot"
      title: "Ribocutter"
      ylab: "Percentage reads targeted"
      ymax: 100
      ymin: 0
    pca:
      section_name: "PCA Analysis"
      description: "This plot shows the first two components from a principal component analysis on RPF counts from FeatureCounts and P-site counts on CDS."
sp:
  ribocutter:
    fn: "ribocutter_mqc.tsv"
  pca:
    fn: "pca_mqc.png"


export_plots: false