name: riboseq-flow-github-actions
run-name: ${{ github.actor }} is using GitHub Actions
on: 
  pull_request:
    branches:
      - main
      - dev
jobs:
  test-riboseq-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"
      - name: Run pipeline with test data    
        run: |
            nextflow run ${GITHUB_WORKSPACE} -profile github,docker --outdir ./results